source "https://rubygems.org"

ruby "${{ values.rubyVersion }}"

gem "rails", "~> ${{ values.railsVersion }}.0"

{%- if values.database == "postgresql" %}
gem "pg", "~> 1.5"
{%- elif values.database == "mysql" %}
gem "mysql2", "~> 0.5"
{%- else %}
gem "sqlite3", "~> 1.7"
{%- endif %}

gem "puma", "~> 6.0"
gem "bootsnap", require: false

{%- if values.apiOnly %}
gem "rack-cors"
{%- endif %}

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development do
  gem "listen"
end
